/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * [./src/constants.cjs]{@link ./src/constants.cjs}
 * 
 **/
const constants = {
    COLOR_TABLE: [
        "#d2466e",                  // Error context color
        "#FFA07A",                  // Default context color
        "#FF7F50",
        "#FF6347",
        "#FFE4B5",
        "#ADFF2F",
        "#808000",
        "#40E0D0",
        "#1E90FF",
        "#EE82EE",
        "#708090",
        "#DEB887",
        "#FE642E",
        "#210B61",
        "#088A4B",
        "#5E610B",
        "#FA8258",
        "#088A68",
        "#B40431",
    ],
    SYSTEM: {
        BROWSER: "BROWSER",
        NODE: "NODE"
    }

}; 

export const COLOR_TABLE = constants.COLOR_TABLE;
export const SYSTEM = constants.SYSTEM;