/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * [example/cjs/contexts-def.cjs]
 * 
 **/    
const constants = {
    LOG_CONTEXT: {STANDARD: {}, TEST: {color: "red"}, C1: null, C2: null, C3: null, DEFAULT: {}},
    LOG_TARGETS: {DEV: {}, USER: {user: true}}
}

export const LOG_CONTEXT = constants.LOG_CONTEXT
export const LOG_TARGETS = constants.LOG_TARGETS