name: Test
env:
  ANALOGGER_APP_NAME: "release/analogger"
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
      - ".vscode/**"
jobs:
  run-test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Check out Git repository
        uses: thimpat/analogger/.github/actions/checkout@ci
      - name: Install dependencies
        shell: powershell
        run: |
          npm ci install
      - name: Generate AnaLogger for browsers
        shell: powershell
        run: |
          npm run build:esm:browser
      - name: Generate AnaLogger for terminals
        shell: powershell
        run: |
          npm run build:esm:terminal
      - name: Test
        shell: powershell
        run: |
          npm run lint
          npm test
